### ISSUE TITLE
Can't Launch Console Instance

### ISSUE THREAD

**Issue by SK83RJOSH** [footballhead/love-launcher#1]
Adding --console to your lovepath doesn't create an instance of love with a console, or one at all really. 

This is obviously because --console is expected to be at the end of your launch parameters, so I propose adding an extra setting that will properly dispatch this launch parameter.

**Comment by footballhead** [comment]
Thanks for reporting this issue! The problem should be resolved with commit 8038af8356967e2e1beed823671bed48991dbebc and release v0.3.0 (05f4c495e14bc7a1959adfbd9d4c75f082f2803d)

The value of lovepath is fed directly to Atom as the command to launch in BufferedProcess, so having a lovepath of `love --console` will make Atom search for the `love --console` executable (which is most likely not installed and not what you wanted in the first place).

Options must be given to BufferedProcess separately. I could parse lovepath to look for options but that sounds messy. Instead, I've added the `Loveopts` setting whose value will be passed as arguments to BufferedProcess; **this is where you'd put `--console`.**

FWIW it doesn't really matter where --console is placed on the command-line, as long as it's understood to be an argument and not part the executable name itself (you can try this on Linux, etc).

I hope this fixes the problem!

**Comment by SK83RJOSH** [comment]
Cheers, that solves this issue quite elegantly! Oh, and sorry for the assumption there, didn't realize BufferedProcess worked that way. Figured it must have been some odd querk having to do to the order (which I thought was odd but commented on nonetheless). :)

**Comment by endlesstravel** [comment]
I'm using Atom 1.7.1 + love2d 10.x on Windows and it can't show love console when I use Atl+L.
I am already add "t.console = true" in "function love.conf(t)" at "conf.lua" file and add "--console" in "love option".
And the version of launcher is 0.5

**Comment by endlesstravel** [comment]
Oh, It show love2d console when I launcher love2d v0.8.0 !
I believe it cause by love2d v0.10.x it self.

**Comment by footballhead** [comment]
Hmmm, I can't get it to work either... but it looks like an upstream issue: I can't get `--console` to work running `love.exe` from the command-line. It seems that between 0.9.1 and 0.9.2 some changes were made to how `--console` is treated. I've opened issue #8 for further investigation.

**Comment by SK83RJOSH** [comment]
It's worth mentioning that I experienced this issue as well, and my workaround was adding the following to conf.lua:

```
io.stdout:setvbuf('no')
```

This doesn't enable Love to create a console window but it does enable Love to output to the Atom developer console in real time.

**Comment by endlesstravel** [comment]
@SK83RJOSH  Real great idea! Thanks for your advice!
