### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by josiahdowdy** [footballhead/love-launcher#13]
Has anyone gotten this working on Mac OS X?

**Comment by footballhead** [comment]
Just tried and it works. I downloaded the .zip, extracted, put the .app into Applications, then set **LÖVE PATH** to `/Applications/love.app/Contents/MacOS/love`.

![love-launcher-settings](https://user-images.githubusercontent.com/3687359/33446058-de2d37ea-d5cc-11e7-82b1-9072bb8b2890.png)

I'll update the README to include this.

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
