### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by ErtYwek** [footballhead/love-launcher#14]
Just doesn't. In around 2018 it worked well but with the new version of Atom, it shows an error. Something about no internal '"love"'. 

> Error running LOVE.
> 
> '"love"' is not recognized as an internal or external command,
> operable program or batch file.
>

**Comment by Kyllingene** [comment]
Try adding love.exe to Path.

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
