### ISSUE TITLE
Launch multiple versions of LÖVE

### ISSUE THREAD

**Issue by HugoBDesigner** [footballhead/love-launcher#16]
I realize this is an very niche case, but every once in a while I'll open a LÖVE project that runs at a different version than what I have set up for Atom, and while changing the `love.exe` path is super easy, one thing I miss from Notepad++ was the ability to bind multiple keys to multiple LÖVE versions. So I was wondering if a similar feature could be implemented into Love Launcher.

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
