### ISSUE TITLE
Nothing sent to Love2D

### ISSUE THREAD

**Issue by RealityFix** [footballhead/love-launcher#4]
When I run Love nothing is sent to it and I get the "No game" splash screen. I'm using atom-windows.zip from here: https://github.com/atom/atom/releases/tag/v1.4.2

Not sure what is wrong.

**Comment by footballhead** [comment]
Hi there,

Things seem to be working on my end... Do you have a project folder open? Is `main.lua` in the root?

![lovelauncher](https://cloud.githubusercontent.com/assets/3687359/12870376/c170826e-cd0f-11e5-8ce1-5943a8ad8dd8.png)

Either use _File -> Open Folder,_ or right click on the sidebar and select _Add Project Folder_. Yeah, it's not the best way to do it... I should look to see if a `main.lua` is open and use that.

Another thing to check is if the _Love Path_ config variable points to `love.exe`; it defaults to `C:\Program Files (x86)\love\love.exe` which can present problems if the 64 bit version of Love is installed.

Let me know if you're still having problems.

**Comment by Zeloii** [comment]
I also have this issue, it runs the program but does not "send the code"

I ran a folder with a file called main.lua with the following code:
`function love.draw()
    love.graphics.setColor( 255, 255, 0, 255 )
    love.graphics.rectangle( "fill", 10, 10, 100, 100 )
end`

I used alt+L on the file, and it ran in love2d but did not show any rectangle?

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
