### ISSUE TITLE
Save on launch?

### ISSUE THREAD

**Issue by premek** [footballhead/love-launcher#7]
To consider - save all the opened files (or all in the current project?) before launching love? It may be configurable

**Comment by footballhead** [comment]
Thanks for the suggestion, I like it! I'll look into adding it

**Comment by kraxarn** [comment]
Would really want this. Is there any workaround for it atm, since it hasn't been added yet?

**Comment by footballhead** [comment]
Added with commit 52c17805939dcf02d779231da6d2d2c223048b9d, should be released as v0.7.0
